pinecone:
  index_name: "cooking-helper"
  dimension: 1024  # Cohere embed-english-v3.0 returns 1024-dimensional vectors

pdf_paths:
  - path: "data/breakfast/Masala Dosa Recipe (Restaurant Style) - Swasthi's Recipes.pdf"
    namespace: "masaladosa"
  - path: "data/breakfast/Upma Recipe (Rava Upma) - Swasthi's Recipes.pdf"
    namespace: "upma"
  - path: "data/dessert/Gulab Jamun Recipe - Swasthi's Recipes.pdf"
    namespace: "gulabjamun"
  - path: "data/dessert/Kheer Recipe (Rice Kheer) - Swasthi's Recipes.pdf"
    namespace: "kheer"
  - path: "data/non_veg_curry/Chicken Bhuna Masala Recipe - Swasthi's Recipes.pdf"
    namespace: "chickenbhunamasala"
  - path: "data/non_veg_curry/Chicken Butter Masala - Swasthi's Recipes.pdf"
    namespace: "chickenbuttermasala"
  - path: "data/rice_non_veg/Chicken Biryani Recipe - Swasthi's Recipes.pdf"
    namespace: "chickenbiryani"
  - path: "data/rice_veg/Pulao Recipe _ Veg Pulao _ Vegetable Pulao _ Pulav - Swasthi's Recipes.pdf"
    namespace: "pulao"
  - path: "data/snacks/Onion Bhaji Recipe (Better than Restaurant) - Swasthi's Recipes.pdf"
    namespace: "onionbhaji"
  - path: "data/snacks/Samosa Recipe (Punjabi Potato Samosa) - Swasthi's Recipes.pdf"
    namespace: "samosa"
  - path: "data/veg_curry/Aloo Gobi Masala - Swasthi's Recipes.pdf"
    namespace: "aloogobi"
  - path: "data/veg_curry/Baingan Bharta Recipe (Eggplant Bharta) - Swasthi's Recipes.pdf"
    namespace: "bainganbharta"


chunking:
  chunk_size: 300
  chunk_overlap: 50

pdf_summary: |
  - The PDFs contain comprehensive Indian recipes categorized under breakfast, dessert, curry (veg and non-veg), rice dishes, and snacks.
  - In breakfast - masaladosa and upma recipes are included.
  - In dessert - gulab jamun and kheer recipes are included.
  - In non-veg curry - chicken bhuna masala and chicken butter masala recipes are included.
  - In rice dishes - chicken biryani and pulao recipes are included.
  - In snacks - onion bhaji and samosa recipes are included.
  - In veg curry - aloo gobi and baingan bharta recipes are included.
  - Each recipe document typically includes:
    - A detailed list of **Ingredients**, with quantity and preparation notes.
    - Step-by-step **Instructions** or **cooking procedures** that cover traditional and restaurant-style techniques.
    - Optional cooking **tips** and alternatives for ingredients.
    - A section on **Nutrition facts**, covering approximate calorie count, protein, fat, and carbohydrate content per serving.
  - These PDFs are sourced from Swasthi’s Recipes and serve as reliable cooking references for Indian home cooking and culinary learning.
  - The documents serve as the knowledge base for context retrieval by the chatbot for user queries.
  

groq:
  model: gemma2-9b-it
  # model: llama-3.1-8b-instant
  # model: deepseek-r1-distill-llama-70b


# This PDF contains detailed information about Indian food cooking, Indian food ingredients and heritage including:
  # Philosophy of Indian Food  
  # 1.3.1 Pre Ancient Era 
  # 1.3.2 Ancient Era 
  # The Great Indian Cuisine – Key Features  
  # 1.4.1 Classification of Food Based on Nature 
  # 1.4.2 Classification of Food Based on Vargas 
  # 1.4.3 Classification of Foods Based on Nutrients 
  # Regional Influences on Indian Food  
  # 1.5.1 Indian Regional Cuisine at a glance 
  # 1.5.1.1 South India 
  # 1.5.1.2 North-east 
  # 1.5.1.3 North India 
  # 1.5.1.4 Western India 
  # 1.5.1.5 Eastern India
  # - Ingredient lists and spice combinations
  # - Cooking methods for traditional Indian meals
  # For anything else return wikipedia:

